version: '3'

services:
    vimdock:
        image: sameyasu/vimdock
        container_name: vimdock
        hostname: vimdock
        environment:
            - TZ=Asia/Tokyo
            - TERM=xterm-256color
        ports:
            - "10022:22"
        volumes:
            - ../:/host
