version: '3'

services:
    vimdock:
        build:
            context: ./docker/
        container_name: vimdock
        hostname: vimdock
        environment:
            - TZ=Asia/Tokyo
            - TERM=xterm-256color
        command: ["sleep","1000d"]
#        volumes:
#            - /path-to-your-workdir:/host
